"""Approval-gate router.

Manages human-in-the-loop approval requests generated by agent runs.
All endpoints are org-scoped.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Annotated, Any

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from pydantic import BaseModel, Field
from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import TokenPayload, get_current_user
from app.middleware.org_scope import current_org_id
from app.models.audit import ActorType, ApprovalRequest, ApprovalStatus, AuditEventType
from app.services.audit import build_audit_event

router = APIRouter(prefix="/approvals", tags=["approvals"])


class ApprovalResponse(BaseModel):
    """Serialised approval request."""

    id: uuid.UUID
    org_id: uuid.UUID
    run_id: uuid.UUID
    step_id: str
    workflow_id: uuid.UUID
    payload: dict[str, Any]
    context: dict[str, Any] | None = None
    required_role: str
    assigned_to: uuid.UUID | None = None
    status: ApprovalStatus
    decision: dict[str, Any] | None = None
    decided_by: uuid.UUID | None = None
    sla_deadline: datetime
    created_at: datetime
    decided_at: datetime | None = None

    model_config = {"from_attributes": True}


class ApprovalListResponse(BaseModel):
    """Paginated list of approval requests."""

    items: list[ApprovalResponse]
    next_cursor: str | None = None
    total: int


class DecisionRequest(BaseModel):
    """Payload for approving or rejecting an approval request."""

    verdict: ApprovalStatus = Field(..., description="approved or rejected")
    reason: str = Field(..., min_length=1, max_length=2000)
    modified_params: dict[str, Any] | None = None


class ReassignRequest(BaseModel):
    """Payload for reassigning an approval request."""

    assigned_to: uuid.UUID


async def _get_approval_or_404(
    db: AsyncSession,
    *,
    approval_id: uuid.UUID,
    org_id: uuid.UUID,
) -> ApprovalRequest:
    result = await db.execute(
        select(ApprovalRequest).where(ApprovalRequest.id == approval_id, ApprovalRequest.org_id == org_id)
    )
    approval = result.scalar_one_or_none()
    if approval is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error_code": "NOT_FOUND", "message": "Approval request not found"},
        )
    return approval


@router.get("", response_model=ApprovalListResponse)
async def list_pending_approvals(
    request: Request,
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[TokenPayload, Depends(get_current_user)],
    status_filter: ApprovalStatus | None = Query(ApprovalStatus.PENDING, alias="status"),
    assigned_to_me: bool = Query(False),
    cursor: str | None = Query(None),
    limit: int = Query(50, ge=1, le=200),
) -> ApprovalListResponse:
    """List approval requests with cursor-based pagination."""

    org_id = current_org_id(request)
    base_q = select(ApprovalRequest).where(ApprovalRequest.org_id == org_id)

    if status_filter is not None:
        base_q = base_q.where(ApprovalRequest.status == status_filter)
    if assigned_to_me:
        base_q = base_q.where(ApprovalRequest.assigned_to == user.sub)

    count_q = select(func.count()).select_from(base_q.subquery())
    total = (await db.execute(count_q)).scalar_one()
    base_q = base_q.order_by(ApprovalRequest.created_at.desc(), ApprovalRequest.id.desc())

    if cursor is not None:
        try:
            cursor_uuid = uuid.UUID(cursor)
        except ValueError as exc:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail={"error_code": "INVALID_CURSOR", "message": "Malformed cursor"},
            ) from exc

        cursor_row = await db.execute(select(ApprovalRequest.created_at).where(ApprovalRequest.id == cursor_uuid))
        cursor_ts = cursor_row.scalar_one_or_none()
        if cursor_ts is not None:
            base_q = base_q.where(
                (ApprovalRequest.created_at < cursor_ts)
                | ((ApprovalRequest.created_at == cursor_ts) & (ApprovalRequest.id < cursor_uuid))
            )

    result = await db.execute(base_q.limit(limit))
    rows = result.scalars().all()
    return ApprovalListResponse(
        items=[ApprovalResponse.model_validate(row) for row in rows],
        next_cursor=str(rows[-1].id) if len(rows) == limit else None,
        total=total,
    )


@router.post("/{approval_id}/decide", response_model=ApprovalResponse)
async def decide_approval(
    approval_id: uuid.UUID,
    body: DecisionRequest,
    request: Request,
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[TokenPayload, Depends(get_current_user)],
) -> ApprovalResponse:
    """Approve or reject an approval request."""

    org_id = current_org_id(request)
    approval = await _get_approval_or_404(db, approval_id=approval_id, org_id=org_id)

    if body.verdict not in {ApprovalStatus.APPROVED, ApprovalStatus.REJECTED}:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error_code": "INVALID_DECISION", "message": "Verdict must be approved or rejected"},
        )
    if approval.status != ApprovalStatus.PENDING:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error_code": "ALREADY_DECIDED", "message": f"Approval already in '{approval.status.value}' state"},
        )

    now = datetime.now(tz=timezone.utc)
    decision_payload = {
        "verdict": body.verdict.value,
        "reason": body.reason,
        "modified_params": body.modified_params,
    }
    await db.execute(
        update(ApprovalRequest)
        .where(ApprovalRequest.id == approval_id)
        .values(
            status=body.verdict,
            decision=decision_payload,
            decided_by=user.sub,
            decided_at=now,
        )
    )
    await db.flush()
    await db.refresh(approval)

    db.add(
        build_audit_event(
            org_id=org_id,
            event_type=AuditEventType.APPROVAL_DECIDED.value,
            actor_type=ActorType.HUMAN,
            actor_id=str(user.sub),
            payload={"approval_id": str(approval_id), **decision_payload},
            decision="allowed",
            run_id=approval.run_id,
        )
    )

    return ApprovalResponse.model_validate(approval)


@router.post("/{approval_id}/reassign", response_model=ApprovalResponse)
async def reassign_approval(
    approval_id: uuid.UUID,
    body: ReassignRequest,
    request: Request,
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[TokenPayload, Depends(get_current_user)],
) -> ApprovalResponse:
    """Reassign a pending approval request to a different user."""

    approval = await _get_approval_or_404(db, approval_id=approval_id, org_id=current_org_id(request))
    if approval.status != ApprovalStatus.PENDING:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error_code": "NOT_PENDING", "message": "Only pending approvals can be reassigned"},
        )

    await db.execute(
        update(ApprovalRequest).where(ApprovalRequest.id == approval_id).values(assigned_to=body.assigned_to)
    )
    await db.flush()
    await db.refresh(approval)
    return ApprovalResponse.model_validate(approval)
